### ISSUE TITLE
你好，运行时在命令界面报错

### ISSUE THREAD

**Issue by zx-code123** [cleverqin/node-websocket-Chatroom#5]
可以聊天，但是显示一些错误
![image](https://user-images.githubusercontent.com/33643595/77554914-a1dcd780-6ef1-11ea-9b9f-469c3561e2b0.png)
(node:15440) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND ***.**.**.* ***.**.**.*:3306
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
    --------------------
    at Protocol._enqueue (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\node_modules\mysql\lib\Pool.js:48:16)
    at Promise (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\log\DB.js:15:12)
    at new Promise (<anonymous>)
    at Object.query (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\log\DB.js:14:12)
    at Object.executor (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\log\DB.js:33:17)
    at Object.addOne (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\log\User.js:14:15)
    at Object.logLoginMessage (C:\Users\Administrator\Desktop\JS\node-websocket-Chatroom-master\log\index.js:6:12)      (node:15440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by cleverqin** [comment]
我增加了记录登录者账号信息的功能需要配置一下mysql数据库
